version: '3.7'

services:
  events_api:
    environment:
      - MONGO_URL=mongodb://db:27017
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      dockerfile: ./events_api/Dockerfile
    hostname: events_api
    container_name: events_api
    ports:
      - "8000:8000"
    networks:
      - cloud_lab

  files_api:
    environment:
      - MONGO_URL=mongodb://db:27017
      - REDIS_URL=redis://redis:6379
    build:
      context: .
      dockerfile: ./files_api/Dockerfile
    hostname: files_api
    container_name: files_api
    ports:
      - "8001:8001"
    networks:
      - cloud_lab