version: '3.7'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    hostname: db
    container_name: db
    volumes:
      - ./mongo_data:/data/db
    networks:
      - cloud_lab

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    hostname: redis
    container_name: redis
    environment:
      - REDIS_PASSWORD=password123
    networks:
      - cloud_lab

networks:
  cloud_lab:
    driver: bridge
