version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    networks:
      - cloud_lab

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    container_name: grafana
    hostname: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    networks:
      - cloud_lab
